### ISSUE TITLE
more search results

### ISSUE THREAD

**Issue by DooML** [hauxir/rapidbay#1]
it would be cool to have more sites such as yts.lt / 1337x / rarbg, anything else is working just perfectly, thank you.

**Comment by hauxir** [comment]
Will look into that.
An unmentioned feature is that you can also copy and paste a magnet link into the search bar and it will automatically open the file list for that link.

**Comment by DooML** [comment]
Yeah, I've also used that and ran registerProtocolHandler() in the console so I could make it handle the magnet protocol, works flawlessly as an alternative!

**Comment by hauxir** [comment]
That sounds super interesting, do you mind sharing the code you did to do that?

**Comment by hauxir** [comment]
Figured it out:
```javascript
navigator.registerProtocolHandler("magnet", "https://<RAPIDBAY_HOST>/magnet/%s", "RapidBay")
```
Super neat!
Going to add this to the codebase under a special url
something like /registerURI

**Comment by DooML** [comment]
Sorry for the late reply, and yeah it's the same function.

**Comment by hauxir** [comment]
I've added it to the codebase

You can now visit https://<YOUR HOST>/registerHandler and it should run the code above in your browser to handle magnet links
