### ISSUE TITLE
development is active? I would like to contribute

### ISSUE THREAD

**Issue by joaotolovi** [hauxir/rapidbay#25]

**Comment by hauxir** [comment]
sure, what would you like to add?

**Comment by joaotolovi** [comment]
> sure, what would you like to add?

I really liked the project congratulations, I will study the source code and try to help. Do you have a purpose for the system? New features you would like to add? What end result would you like to have? _sorry my english, i'm from brazil_

**Comment by hauxir** [comment]
You could continue with this https://github.com/hauxir/rapidbay/pull/11

**Comment by joaotolovi** [comment]
OK. A doubt, it downloads the whole file before playing or plays in real time in streaming?

**Comment by hauxir** [comment]
it downloads the file to the server first and then you can stream it.
